version: "2"
services:
  aria2:
    image: superng6/baidupcs-web
    container_name: baidupcs-web
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
    volumes:
      - /path/to/appdata/config:/config
      - /path/to/downloads:/root/Downloads
    ports:
      - 5299:5299
    restart: unless-stopped
